ngsweb:
    default_title: "NGS's wonderland!"
    webstructure:
        "[/*]":
            servertype: "html_folder"
            custom:
                headInjectFile: "injects/testinject.html"
                sourcefolder: "testweb"
        "[/Styles/*]":
            servertype: "css_folder"
            custom:
                sourcefolder: "testweb/Styles"
        "[/Images/*]":
            servertype: "image_folder"
            custom:
                sourcefolder: "testweb/Images"
        "[/Scripts/*]":
            servertype: "js_folder"
            custom:
                sourcefolder: "testweb/Scripts"
        "[/hudder/*]":
            servertype: "html_folder"
            custom:
                headInjectFile: "injects/testinject.html"
                sourcefolder: "testweb/hudder"
        "[/hudder/Images/*]":
            servertype: "image_folder"
            custom:
                sourcefolder: "testweb/hudder/Images"
        "[/hudder/base.js]":
            servertype: "raw_file"
            custom:
                file: "testweb/hudder/base.js"
                contenttype: "text/javascript"
server:
    port: 9090